on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  INSTANCE: "Writerside"
  ARTIFACT: "SPP-Primer.zip"
  DOCKER_VERSION: "233.14389"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docs using Writerside Docker builder
        uses: Jetbrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7
